// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vw93Z5k6F0YtNhHuoKdmNq4rJmnFbWs',
    appId: '1:256666824774:web:97fd2141d4a711067a5a47',
    messagingSenderId: '256666824774',
    projectId: 'ndpro-3e160',
    authDomain: 'ndpro-3e160.firebaseapp.com',
    storageBucket: 'ndpro-3e160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0IogZyY7PcQsCwiOL8lcKvf99yLesvA',
    appId: '1:256666824774:android:a331d303ac3d00547a5a47',
    messagingSenderId: '256666824774',
    projectId: 'ndpro-3e160',
    storageBucket: 'ndpro-3e160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuaLYYiBYZAZsQtXGli-EXCN1dlfqgdbQ',
    appId: '1:256666824774:ios:8b552d34945f21387a5a47',
    messagingSenderId: '256666824774',
    projectId: 'ndpro-3e160',
    storageBucket: 'ndpro-3e160.appspot.com',
    iosBundleId: 'com.example.flutterNd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuaLYYiBYZAZsQtXGli-EXCN1dlfqgdbQ',
    appId: '1:256666824774:ios:d080ade6e3ffb3fb7a5a47',
    messagingSenderId: '256666824774',
    projectId: 'ndpro-3e160',
    storageBucket: 'ndpro-3e160.appspot.com',
    iosBundleId: 'com.example.flutterNd.RunnerTests',
  );
}
